source("_targets.R")
#tar_invalidate(hyperr8_analysis)
tar_make()
#system("quarto render figures.qmd")
system("quarto render outreach.qmd")
system("open outreach.html")
#system("quarto render diagram.qmd")
